# Generated by Django 5.1.6 on 2025-03-11 04:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GridsPopulation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_region', models.CharField(max_length=255)),
                ('note', models.TextField()),
                ('grid_id', models.IntegerField()),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('f0_14', models.IntegerField()),
                ('f15_25', models.IntegerField()),
                ('f26_35', models.IntegerField()),
                ('f36_45', models.IntegerField()),
                ('f46_55', models.IntegerField()),
                ('f56_65', models.IntegerField()),
                ('f66', models.IntegerField()),
                ('total_sum_population', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('is_deleted', models.BooleanField()),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('name_region_kz', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'grids_population',
            },
        ),
    ]
