# Generated by Django 5.1.6 on 2025-03-11 04:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressCityDistrict',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_kz', models.CharField(max_length=255)),
                ('name_ru', models.CharField(max_length=255)),
                ('response_name_kz', models.CharField(max_length=255)),
                ('response_name_ru', models.CharField(max_length=255)),
                ('gerb_img', models.CharField(blank=True, max_length=255, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('marker', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('city_id', models.BigIntegerField()),
                ('akim_id', models.IntegerField()),
            ],
            options={
                'db_table': 'address_city_districts',
            },
        ),
        migrations.CreateModel(
            name='EDCHexa500x500',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('left', models.FloatField()),
                ('top', models.FloatField()),
                ('right', models.FloatField()),
                ('bottom', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'db_table': 'edc_hexa_500x500',
            },
        ),
    ]
